apiVersion: v1
kind: ConfigMap
metadata:
  name: color-config
data:
  file_path: /mnt/config/color.txt
  color.txt: green
  TEST.JS: |
    console.log("Hello from TEST.JS");
    console.log("This is a multi-line string in a ConfigMap");
