apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../_network-policies

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: mongodb-root-creds
    envs:
      - .env.root-cred.dev
  - name: mongodb-colordb-creds
    envs:
      - .env.colordb-cred.dev
