apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-ingress
  annotations:
    # kubernetes.io/ingress.global-static-ip-name: color-api-dev
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: prod-mc
spec:
  rules:
    - host: prod.experts247.online
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: color-svc
                port:
                  number: 80
