apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-svc.yaml
  - mongodb-ss.yaml
  - ./network-policies/allow-traffic-from-color-app.yaml

configMapGenerator:
  - name: mongodb-init-colordb
    files:
      - mongo-init.js
